var namee = "Furqan";
var namee_lower = namee.toLowerCase();
var namee_upper = namee.toUpperCase();
var namee_local_lower = namee.toLocaleLowerCase();
var namee_local_upper = namee.toLocaleUpperCase();
console.log(namee);
console.log(namee_lower);
console.log(namee_upper);
console.log(namee_local_lower);
console.log(namee_local_upper);
